language: csharp
mono: none
dotnet: 5.0
solution:
services: 
  - docker
script:
  - dotnet test SucceSales.Tests/SucceSales.Tests.csproj --configuration Release --nologo --blame

after_success:
  - | 
    if [ "$TRAVIS_BRANCH" == "main" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker build -t $DOCKER_USERNAME/succesales:latest .;
      docker push $DOCKER_USERNAME/succesales:latest;
    fi